# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0b05723d101b0ee743dc9add1266698f959af76a9c92f49f3120bb149e83cbf63ea73ec435d9002c2927c8376677f9f826c39ff8eed043eabe451b1e8ecf30f

test:
  secret_key_base: be47b05e1282aad93f943fc03f20880289ef38f0145d7755a7ec01eefb293a754405126acbcc851e6a2d54fd71c579e06838284f76bd21308177f11514475a65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["BLOGBOX_SECRET_KEY_BASE"] %>
